### ISSUE TITLE
Integration with LSP package basic setup?

### ISSUE THREAD

**Issue by craigmac** [sublimelsp/LSP-html#14]
Is there a reason a basic setup like:

```json
"vscode-html": 
{
  "command": ["html-languageserver", "--stdio"],
  "document_selector": "text.html.basic"
},
```

Can't be put into the default LSP.sublime-settings file? For a newcomer the experience is super confusing: I install LSP then LSP-HTML, but then there's no option to enable HTML server globally, even though there is one for "vscode-css". Took me a lot of research and configuring to get the HTML language server to start and work with HTML files. There must be a more user-friendly way?

**Comment by jfcherng** [comment]
LSP-html should auto work out-of-box.

**Comment by predragnikolic** [comment]
Just a small intro.
There are two ways of setting up any programming laguage with LSP:

1. First way. Install LSP-* plugins (LSP-css, LSP-html, LSP-typescript...). These are all plugins that can be installed from Package Control, and they are usually pre-configured... you just install them and they should work(in the README of each plugin you may see if a plugin requires you to install something for it to work, like a syntax). This is the way I recommend because it is easy. 

But unless that there isn't a LSP-plugin configured for a language, I would suggest the second option.  
  
2. And the second option is to manually configure the language server, by putting the language congratulation(you can see in the lsp docs on how to configure those) in the `clients` key of the `LSP.sublime-settings` file and manually installing the language server from `npm`, `pip` .... or whatever the installation instruction for a given language server are. Obviously this way is a bit more involved and more prone to human error. 

That said, there is no need for someone to configure a language server in the `clients` LSP.sublime-setting and yet have the same sever installed through Package Control :)

**Comment by rchl** [comment]
I understand that it can be confusing how LSP-* packages, `clients` configuration object and command palette `Enable server globally` cooperate.

I don't understand that part though:

> Took me a lot of research and configuring to get the HTML language server to start and work with HTML files. There must be a more user-friendly way?

since, as @jfcherng said, LSP-html should just work out of the box (at least after an additional restart after installing).

Unless you had issues with npm/node not being in the PATH but that problem is relevant for either method.

I guess this issue/question is more general and belongs more in the LSP repo.
Not sure how it could be addressed/simplified though.

**Comment by jfcherng** [comment]
> since, as @jfcherng said, LSP-html should just work out of the box (with an additional restart after installing, at least - I wonder if that part can also add to confusion).

Maybe we can make the "restart" hinting with a dialog box (assuming it won't happen frequently, so won't be too annoying).

**Comment by craigmac** [comment]
Thanks for the replies, I will retry the process tonight with “subl —clean” and see what my problem was/is and report back.

**Comment by craigmac** [comment]
OK, so my issue appears to have been unrelated to your package: I use 'nvm' to manage and switch Node versions, which installs from shell scripts to manage pointing to the correct node, and does some trickery with $PATH which according to one of their issues does not enable GUI applications to pickup the node binary. However, the correct node binary works on the shell, and if I start sublime via CLI, lsp-html works as intended. A message was buried in the panel lsp debug logs about not finding 'node', which tipped me off. Thanks for your help!

**Comment by rchl** [comment]
I don't know on which platform you are on but if you put the NVM initialization script in the right place then ST will be able to use the node version that NVM manages.

You can read through https://github.com/sublimelsp/LSP-vue/issues/20 for more hints.

**Comment by craigmac** [comment]
Linux Mint Debian edition atm, also Ubuntu 20.04 LTS and OS X (and Win 10 at work). Interesting discussion, I don't think I'm prepared to head down that rabbit hole just yet, I'll stick with running ST from CLI instead. I guess there's a price to pay for all that shim magic that nvm/asdf does.
