### ISSUE TITLE
How do I set the indent width for html.format?

### ISSUE THREAD

**Issue by txtsd** [sublimelsp/LSP-html#16]
7 spaces is dummy T H I C C, and I'm unable to find a setting for it.

**Comment by rchl** [comment]
It's inferred from open view (using `view.settings().get('tab_size')`). If that's not correctly set then the server will also use incorrect value. There is no separate setting for it.

**Comment by txtsd** [comment]
Can we have an options key like here: https://github.com/sublimelsp/LSP-vue/blob/80ef520401f83e6959e5eb8a85aaf79b7513c631/LSP-vue.sublime-settings#L34

My global tab size is 4, however I use 2 spaces in html files. I'd like to be able to set it explicitly.

**Comment by jfcherng** [comment]
> My global tab size is 4, however I use 2 spaces in html files.

Syntax-specific settings is not working?

**Comment by rchl** [comment]
> My global tab size is 4, however I use 2 spaces in html files. I'd like to be able to set it explicitly.

I think that would be a wrong solution to your problem because if ST has detected indentation to be 4, you'll still get issues irrespective of the `LSP-html` itself. Like, pressing enter to add new, indented line will use 4 spaces instead of your preferred 2.

Syntax-specific setting seem like a proper solution to your problem.

Also maybe you should disable `detect_indentation` so that ST doesn't try to change it (also in syntax-specific settings).

**Comment by txtsd** [comment]
I wasn't aware of syntax-specific settings. I set the `tab_size` to 2 for html files and it works as expected.
Thank you!
